import type { Metadata } from "next";
import "./globals.css";
import { fontInter } from "~/shared/assets/fonts/inter";
import { cn } from "~/shared/lib/utils";
import { fontManrope } from "~/shared/assets/fonts/manrope";
import { ThemeProvider } from "./_theme";

export const metadata: Metadata = {
	title: "BitRunes",
	description: "Generated by create next app",
};

const fontVariables = [fontInter.variable, fontManrope.variable]

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={cn(...fontVariables)}>
				<ThemeProvider
					attribute="class"
					defaultTheme="dark"
					enableSystem
					disableTransitionOnChange
				>
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
