import "./globals.css";

import type { Metadata } from "next";
import { fontInter } from "~/shared/assets/fonts/inter";
import { cn } from "~/shared/lib/utils";
import { fontManrope } from "~/shared/assets/fonts/manrope";
import { ThemeProvider } from "./_theme";
import { PageRoot } from "~/pages/root";

export const metadata: Metadata = {
	title: "BitRunes",
	description: "Generated by create next app",
};

const fontVariables = [fontInter.variable, fontManrope.variable]

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={cn(...fontVariables, 'bg-body light:bg-white-gradient')}
				style={{
					backgroundImage: 'radial-gradient(rgb(189 189 189 / 4%) -25%, rgba(255, 255, 255, 0))'
				}}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="dark"
					enableSystem
					disableTransitionOnChange
				>
					<PageRoot>
						{children}
					</PageRoot>
				</ThemeProvider>
			</body>
		</html>
	);
}
